OC.L10N.register(
    "richdocumentscode",
    {
    "Built-in CODE Server" : "خادوم كولّابورا CODE المُدمَج",
    "Collabora Online - Built-in CODE Server" : "كولّابورا على الوب. خادوم كولّابورا CODE المُدمج",
    "Built-in Collabora Online Development Edition (CODE) server for local testing and non-production use" : "نسخة خادوم مُدمج لتطوير كولّابورا على الوب (CODE) للاختبار المحلي في بيئة غير فعلية. ",
    "This app has to be installed and used together with the **[Nextcloud Office](https://apps.nextcloud.com/apps/richdocuments)** integration app.\n\nCollabora Online is a powerful LibreOffice-based online office suite with collaborative editing, which supports all major documents, spreadsheet and presentation file formats and works together with all modern browsers.\n\nThis app provides a built-in server with all of the document editing features of Collabora Online. Easy to install, for personal use or for small teams. A bit slower than a standalone server and without the advanced scalability features.\n\nThe download is rather big so it is possible you experience a time-out when using the web interface. You can use the OCC command line tool to install the built-in server:\n\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:install richdocumentscode\n```\nWhere `wwwrun` is the user of your web server. This is ```www-data``` on Debian, Ubuntu and derivatives, `wwwrun` on SUSE based distributions, `apache` on Red Hat/Fedora and `http` on Arch linux and derivatives.\n\nUpdates can be done like this:\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:update --all\n```\n\nOf course, alternatively you could increase memory usage and PHP time-outs by default, see the [Nextcloud documentation.](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=php%20timeout#configuring-your-web-server)" : "هذا التطبيق يلزم تثبيته ليستخدم مع تطبيق التكامل **[مكتب نكست كلاود Nextcloud Office](https://apps.nextcloud.com/apps/richdocuments)**. \n\nCollabora Online هي رزمة برمجية مكتبية قوية تعمل عبر الإنترنت؛ و هي مبينة على أساس التطبيق \"ليبر أوفيس\" LibreOffice و تتميز بإمكانية التحرير التعاوني، و تدعم جميع تنسيقات المستندات و جداول البيانات و ملفات العروض التقديمية الرئيسية و تعمل مع جميع المتصفحات الحديثة. \n\nيوفر هذا التطبيق خادمًا مدمجًا به جميع ميزات تحرير المستندات في Collabora Online. سهل التركيب، للاستخدام الشخصي أو للفرق الصغيرة. أبطأ قليلاً من الخادم المستقل و بدون ميزات متقدمة من حيث القابلية للتوسع. \n\nحجم التنزيل كبير جداً؛ لذا من الممكن أن تواجه تأخيراً عند استخدام واجهة الويب. \n\nيمكنك استخدام الأمر السطري OCC لتثبيت الخادم المدمج كالتالي: \n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:install richdocumentscode\n```\nحيث `wwwrun` هو مستخدم خادوم الويب لديك. و يكون `www-data` في حالة Debian و Ubuntu \nومشتقاتهما، و`wwwrun` على التوزيعات القائمة على SUSE، و `Apache` على Red Hat/Fedora و `http` على Arch linux ومشتقاته. \n\nيمكن إجراء التحديثات على النحو التالي: \n\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:update --all\n```\nو يمكنك، بدلاً عن ذلك، زيادة الاستخدام التلقائي للذاكرة و للمُهل الزمنية time-outs في PHP. \n\nراجع [وثائق نكست كلاود]\n(https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=php%20timeout#configuring-your-web-server)",
    "Your system is ARM64, but you have installed the x86_64 version of the app. Please remove this and" : "نظامك ARM64؛ لكنك قمت بتنصيب نسخة التطبيق الخاصة بـ x86_64. رجاءً أزلها و  ",
    "install the correct version from the Nextcloud App Store." : "نصّب النسخة الصحيحة من متجر تطبيقات نكست كلاود.",
    "Your system is x86_64, but you have installed the ARM64 version of the app. Please remove this and" : "نظامك x86_64؛ لكنك قمت بتنصيب نسخة التطبيق الخاصة بـ ARM64. رجاءً أزلها و ",
    "You have the Collabora Online app enabled. For further information and configuration, please check:" : "تطبيق كولّابورا على الوب مُفعّلٌ عندك. للمزيد من المعلومات و التهيئة، رجاءً أنظر:",
    "Administration settings > Nextcloud Office" : "إعدادات الإدارة Administration settings  > نكست كلاود أوفيس Nextcloud Office",
    "The Built-in CODE Server is designed to work with the Nextcloud Office app." : "خادوم الـ CODE المُدمَج مُصمّم للعمل مع تطبيق نكست كلاود أوفيس Nextcloud Office.",
    "Install it from the Nextcloud App Store." : "نصّبه من متجر تطبيقات نكست كلاود",
    "An error occurred while trying to check your Collabora Online app installation. You may report this error\n                with the tag: <em>richdocuments-EnabledCheckFailed</em>" : "حدث خطأ عند محاولة التحقُّق من تنصيب تطبيق كولّابورا Collabora على الوب عندك. يمكنك الإبلاغ عن هذا الخطأ باستخدام الوسم:  <em>richdocuments-EnabledCheckFailed</em>"
},
"nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;");
