OC.L10N.register(
    "richdocumentscode",
    {
    "Built-in CODE Server" : "組み込みCODEサーバー",
    "Collabora Online - Built-in CODE Server" : "Collabora Online - 組み込みCODEサーバー",
    "Built-in Collabora Online Development Edition (CODE) server for local testing and non-production use" : "ローカルテストおよび非実稼働で使用するための組み込みのCollaboraOnline Development Edition(CODE)サーバー",
    "This app has to be installed and used together with the **[Collabora Online](https://apps.nextcloud.com/apps/richdocuments)** app.\n\nCollabora Online is a powerful LibreOffice-based online office suite with collaborative editing, which supports all major documents, spreadsheet and presentation file formats and works together with all modern browsers.\n\nThis app provides a built-in server with all of the document editing features of Collabora Online. Easy to install, for personal use or for small teams. A bit slower than a standalone server and without the advanced scalability features.\n\nThe download is rather big so it is possible you experience a time-out when using the web interface. You can use the OCC command line tool to install the built-in server:\n\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:install richdocumentscode\n```\nWhere `wwwrun` is the user of your web server. This is ```www-data``` on Debian, Ubuntu and derivatives, `wwwrun` on SUSE based distributions, `apache` on Red Hat/Fedora and `http` on Arch linux and derivatives.\n\nUpdates can be done like this:\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:update --all\n```\n\nOf course, alternatively you could increase memory usage and PHP time-outs by default, see the [Nextcloud documentation.](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=php%20timeout#configuring-your-web-server)" : "このアプリは、**[Collabora Online](https://apps.nextcloud.com/apps/richdocuments)**アプリと一緒にインストールして使用します。\n\nCollabora Onlineは、共同編集機能を備えた強力なLibreOfficeベースのオンライン・オフィススイートで、すべての主要なドキュメント、スプレッドシート、プレゼンテーションファイルフォーマットをサポートし、最新のすべてのブラウザーで動作します。\n\nこのアプリは、Collabora Onlineのドキュメント編集機能をすべて備えた組み込みサーバーを提供します。個人でも少人数のチーム向けに簡単にインストールできます。その為、スタンドアロンのサーバーに比べてやや遅く、高度なスケーラビリティ機能もありません。\n\nダウンロードの容量が大きいため、ウェブインターフェイスを使用する際にタイムアウトが発生する可能性があります。OCCコマンドラインツールを使って、ビルトインサーバーをインストールすることもできます。\n\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:install richdocumentscode\n```\nここで、`wwwrun`はウェブサーバーのユーザー名です。Debian、Ubuntuおよびその派生版では `www-data` 、SUSEベースのディストリビューションでは `wwwrun` 、Red Hat/Fedoraでは `apache` 、Arch Linuxおよびその派生版では `http` となります。\n\nアップデートは以下のように行います。\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:update --all\n```\n\nもちろん、デフォルト設定からメモリ使用量やPHPのタイムアウトを増やすこともできます。[Nextcloud documentation](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=php%20timeout#configuring-your-web-server)を参照してください。",
    "Your system is ARM64, but you have installed the x86_64 version of the app. Please remove this and" : "システムは ARM64 ですが、 x86_64 版のアプリがインストールされています。このアプリを削除してください。",
    "install the correct version from the Nextcloud App Store." : "Nextcloud App Store から正しいバージョンをインストール",
    "Your system is x86_64, but you have installed the ARM64 version of the app. Please remove this and" : "システムは x86_64 ですが、 ARM64 版のアプリがインストールされています。このアプリを削除してください。",
    "You have the Collabora Online app enabled. For further information and configuration, please check:" : "Collabora Online アプリが有効になっています。詳細や設定についてはこちらをご確認ください : ",
    "Settings > Administration > Collabora Online" : "設定 > 管理 > Collabora Online",
    "Built-in CODE server is designed to work with the usual Collabora Online app." : "組み込みCODEサーバーは、通常のCollabora Onlineアプリと連動するように設計されています。",
    "Install it from the Nextcloud App Store." : "Nextcloud App Store からインストール",
    "An error occurred while trying to check your Collabora Online app installation. You may report this error\n                with the tag: <em>richdocuments-EnabledCheckFailed</em>" : "Collabora Online アプリのインストールを確認しようとしたときにエラーが発生しました。このエラーを報告してください。\nタグ: <em>richdocuments-EnabledCheckFailed</em>"
},
"nplurals=1; plural=0;");
