OC.L10N.register(
    "richdocumentscode",
    {
    "Built-in CODE Server" : "Встроенный CODE Server",
    "Collabora Online - Built-in CODE Server" : "Collabora Online - встроенный CODE Server",
    "Built-in Collabora Online Development Edition (CODE) server for local testing and non-production use" : "Встроенный Collabora Online Development Edition (CODE) сервер для локального тестирования и не производственного использования",
    "This app has to be installed and used together with the **[Collabora Online](https://apps.nextcloud.com/apps/richdocuments)** app.\n\nCollabora Online is a powerful LibreOffice-based online office suite with collaborative editing, which supports all major documents, spreadsheet and presentation file formats and works together with all modern browsers.\n\nThis app provides a built-in server with all of the document editing features of Collabora Online. Easy to install, for personal use or for small teams. A bit slower than a standalone server and without the advanced scalability features." : "Это приложение должно быть использовано и вместе с  **[Collabora Online](https://apps.nextcloud.com/apps/richdocuments)** app.\n\nCollabora Online это мощный, основанный на LibreOffice онлайн офисный пакет с поддержкой коллаборативного редактирования, который поддерживает все основные документы, таблицы и презентационные форматы файлов и работает вместе со всеми современными браузерами.\n\nЭто приложение обеспечивается встроенным сервером со всеми опциями редактирования Collabora Online. Легко устанавливается для личного использования и для небольших команд. Работает немного медленнее чем выделенный отдельный сервер и без продвинутых масштабируемых опций.",
    "You have the Collabora Online app enabled. For further information and configuration, please check:" : "Вы включили Collabora Online app. Для дальнейшей информации и конфигурирования, пожалуйста, проверьте:",
    "Settings > Administration > Collabora Online" : "Настройки > Администрирование > Collabora Online",
    "Built-in CODE server is designed to work with the usual Collabora Online app." : "Встроенный CODE сервер создан для работы с обычным Collabora Online app.",
    "Install it from the Nextcloud App Store." : "Установить это из Nextcloud App Store.",
    "An error occurred while trying to check your Collabora Online app installation. You may report this error\n                with the tag: <em>richdocuments-EnabledCheckFailed</em>" : "Возникла ошибка во время проверки установки Collabora Online app. Вы можете отправить отчет об этой ошибке\n                с этим тэгом: <em>richdocuments-EnabledCheckFailed</em>"
},
"nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n%100>=11 && n%100<=14)? 2 : 3);");
