OC.L10N.register(
    "richdocumentscode",
    {
    "Built-in CODE Server" : "Vstavaný CODE server",
    "Collabora Online - Built-in CODE Server" : "Collabora Online - vstavaný server CODE ",
    "Built-in Collabora Online Development Edition (CODE) server for local testing and non-production use" : "Vstavaný server Collabora Online Development Edition (CODE) na lokálne testovanie a na neprodukčné použitie",
    "This app has to be installed and used together with the **[Collabora Online](https://apps.nextcloud.com/apps/richdocuments)** app.\n\nCollabora Online is a powerful LibreOffice-based online office suite with collaborative editing, which supports all major documents, spreadsheet and presentation file formats and works together with all modern browsers.\n\nThis app provides a built-in server with all of the document editing features of Collabora Online. Easy to install, for personal use or for small teams. A bit slower than a standalone server and without the advanced scalability features.\n\nThe download is rather big so it is possible you experience a time-out when using the web interface. You can use the OCC command line tool to install the built-in server:\n\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:install richdocumentscode\n```\nWhere `wwwrun` is the user of your web server. This is ```www-data``` on Debian, Ubuntu and derivatives, `wwwrun` on SUSE based distributions, `apache` on Red Hat/Fedora and `http` on Arch linux and derivatives.\n\nUpdates can be done like this:\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:update --all\n```\n\nOf course, alternatively you could increase memory usage and PHP time-outs by default, see the [Nextcloud documentation.](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=php%20timeout#configuring-your-web-server)" : "Táto aplikácia musí byť nainštalovaná a používaná spolu s aplikáciou **[Collabora Online](https://apps.nextcloud.com/apps/richdocuments)**.\n\nCollabora Online je výkonný online kancelársky balík založený na LibreOffice so spoločnými úpravami, ktorý podporuje všetky hlavné formáty dokumentov, tabuliek a prezentácií a pracuje so všetkými modernými prehliadačmi.\n\nTáto aplikácia poskytuje zabudovaný server so všetkými funkciami úpravy dokumentov v Collabora Online. Ľahko sa inštaluje, pre osobné použitie alebo pre malé tímy. Trochu pomalšia ako samostatný server a bez pokročilých funkcií škálovateľnosti.\n\nStiahnutie je dosť veľké, takže je možné, že pri používaní webového rozhrania narazíte na časový limit. Na inštaláciu zabudovaného servera môžete použiť nástroj príkazového riadku OCC:\n\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:install richdocumentscode\n```\nKde `wwwrun`  je používateľ vášho webového servera. V Debiane, Ubuntu a odvodených je to ```www-data```, v distribúciách založených na SUSE `wwwrun`, v Red Hat/Fedora `apache` a v Arch linux a odvodených `http`.\n\nAktualizácie je možné vykonať takto:\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:update --all\n```\n\nSamozrejme, alternatívne môžete predvolene zvýšiť využitie pamäte a časové limity PHP, viď [Nextcloud documentation.](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=php%20timeout#configuring-your-web-server)",
    "Your system is ARM64, but you have installed the x86_64 version of the app. Please remove this and" : "Váš systém je ARM64, ale nainštalovali ste verziu aplikácie x86_64. Odstráňte ju a",
    "install the correct version from the Nextcloud App Store." : "Nainštalujte si správnu verziu z obchodu Nextcloud App Store.",
    "Your system is x86_64, but you have installed the ARM64 version of the app. Please remove this and" : "Váš systém je x86_64, ale nainštalovali ste verziu aplikácie ARM64. Odstráňte ju a",
    "You have the Collabora Online app enabled. For further information and configuration, please check:" : "Máte povolenú aplikáciu Collabora Online. Ďalšie informácie a nastavenie nájdete na:",
    "Settings > Administration > Collabora Online" : "Nastavenia> Správa> Collabora Online",
    "Built-in CODE server is designed to work with the usual Collabora Online app." : "Vstavaný server CODE je navrhnutý pre prácu s bežnou aplikáciou Collabora Online.",
    "Install it from the Nextcloud App Store." : "Nainštalujte ho z obchodu Nextcloud App Store.",
    "An error occurred while trying to check your Collabora Online app installation. You may report this error\n                with the tag: <em>richdocuments-EnabledCheckFailed</em>" : "Pri pokuse o kontrolu inštalácie aplikácie Collabora Online sa vyskytla chyba. Túto chybu môžete nahlásiť\n                s označením: <em>richdocuments-EnabledCheckFailed</em>"
},
"nplurals=4; plural=(n % 1 == 0 && n == 1 ? 0 : n % 1 == 0 && n >= 2 && n <= 4 ? 1 : n % 1 != 0 ? 2: 3);");
