OC.L10N.register(
    "richdocumentscode",
    {
    "Built-in CODE Server" : "Уграђени CODE сервер",
    "Collabora Online - Built-in CODE Server" : "Collabora Online - Уграђени CODE сервер",
    "Built-in Collabora Online Development Edition (CODE) server for local testing and non-production use" : "Built-in Collabora Online Development Edition (CODE) сервер за локално тестирање, није за нормалн употребу",
    "This app has to be installed and used together with the **[Collabora Online](https://apps.nextcloud.com/apps/richdocuments)** app.\n\nCollabora Online is a powerful LibreOffice-based online office suite with collaborative editing, which supports all major documents, spreadsheet and presentation file formats and works together with all modern browsers.\n\nThis app provides a built-in server with all of the document editing features of Collabora Online. Easy to install, for personal use or for small teams. A bit slower than a standalone server and without the advanced scalability features.\n\nThe download is rather big so it is possible you experience a time-out when using the web interface. You can use the OCC command line tool to install the built-in server:\n\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:install richdocumentscode\n```\nWhere `wwwrun` is the user of your web server. This is ```www-data``` on Debian, Ubuntu and derivatives, `wwwrun` on SUSE based distributions, `apache` on Red Hat/Fedora and `http` on Arch linux and derivatives.\n\nUpdates can be done like this:\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:update --all\n```\n\nOf course, alternatively you could increase memory usage and PHP time-outs by default, see the [Nextcloud documentation.](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=php%20timeout#configuring-your-web-server)" : "Ова апликација мора да се инсталира заједно са **[Collabora Online](https://apps.nextcloud.com/apps/richdocuments)** апликацијом.\n\nCollabora Online моћна офис свита заснована на Либреофис са заједничким уређивање, подршком за све главне формате фајлова докумената, табела и презентација и која ради у свим модерним интернет прегледачима.\n\nОва апликација обезбеђује уграђени сервер са свим Collabora Online могућнстима уређивања документа. Једноставан је за инсталацију, личну употребу или за мале тимове. Мало је спорији од самосталног сервера и нема напредне могућности прилагођења величине.\n\nПреузимање је прилично велико, па је могуће да искусите истеке времена употребе веб интерфејса. Употребите OCC алат из командне линије да инсталирате уграђени сервер:\n\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:install richdocumentscode\n```\nГде је `wwwrun` корисник вашег веб сервера. То је ```www-data``` на Debian, Ubuntu и сличним, `wwwrun` на дистрибуцијам заснованим на SUSE, `apache` на Red Hat/Fedora и `http` на Arch linux и сличнима.\n\nАжурирања могу да се изврше на следећи начин:\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:update --all\n```\n\nНаравно, могли бисте да увећате подразумевану употребу меморије и  PHP тајмауте, погледајте [Nextcloud документацију.](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=php%20timeout#configuring-your-web-server)",
    "Your system is ARM64, but you have installed the x86_64 version of the app. Please remove this and" : "Ваш систем је ARM64, а инсталирали сте x86_64 верзију апликације. Молимо вас да је уклоните и",
    "install the correct version from the Nextcloud App Store." : "инсталирате исправну верзију из Nextcloud Продавнице апликација.",
    "Your system is x86_64, but you have installed the ARM64 version of the app. Please remove this and" : "Ваш систем је x86_64, а инсталирали сте ARM64 верзију апликације. Молимо вас да је уклоните и",
    "You have the Collabora Online app enabled. For further information and configuration, please check:" : "Укључили сте апликацију Collabora Online. За више информација и начин подешавања, молимо вас да погледате:",
    "Settings > Administration > Collabora Online" : "Подешавања > Администрација > Collabora Online",
    "Built-in CODE server is designed to work with the usual Collabora Online app." : "Уграђени CODE сервер је предвиђен да ради са уобичајеном Collabora Online апликацијом.",
    "Install it from the Nextcloud App Store." : "Инсталирајте га са Nextcloud Продавнице апликација.",
    "An error occurred while trying to check your Collabora Online app installation. You may report this error\n                with the tag: <em>richdocuments-EnabledCheckFailed</em>" : "Дошло је до грешке током провере ваше инсталације Collabora Online апликације. Ову грешку можете да пријавите\n                уз ознаку: <em>richdocuments-EnabledCheckFailed</em>"
},
"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);");
