OC.L10N.register(
    "richdocumentscode",
    {
    "Built-in CODE Server" : "Вбудований сервед CODE",
    "Collabora Online - Built-in CODE Server" : "Collabora Online - вбудований сервер CODE",
    "Built-in Collabora Online Development Edition (CODE) server for local testing and non-production use" : "Вбудований сервер Collabora Online Development Edition (CODE) для локального тестування та непродуктового використання",
    "This app has to be installed and used together with the **[Collabora Online](https://apps.nextcloud.com/apps/richdocuments)** app.\n\nCollabora Online is a powerful LibreOffice-based online office suite with collaborative editing, which supports all major documents, spreadsheet and presentation file formats and works together with all modern browsers.\n\nThis app provides a built-in server with all of the document editing features of Collabora Online. Easy to install, for personal use or for small teams. A bit slower than a standalone server and without the advanced scalability features.\n\nThe download is rather big so it is possible you experience a time-out when using the web interface. You can use the OCC command line tool to install the built-in server:\n\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:install richdocumentscode\n```\nWhere `wwwrun` is the user of your web server. This is ```www-data``` on Debian, Ubuntu and derivatives, `wwwrun` on SUSE based distributions, `apache` on Red Hat/Fedora and `http` on Arch linux and derivatives.\n\nUpdates can be done like this:\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:update --all\n```\n\nOf course, alternatively you could increase memory usage and PHP time-outs by default, see the [Nextcloud documentation.](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=php%20timeout#configuring-your-web-server)" : "Цю програму потрібно встановити та використовувати разом із програмою **[Collabora Online](https://apps.nextcloud.com/apps/richdocuments)**. Collabora Online — це потужний офісний онлайн-пакет на основі LibreOffice із спільним редагуванням, який підтримує всі основні формати документів, електронних таблиць і файлів презентацій і працює разом з усіма сучасними браузерами. Ця програма надає вбудований сервер із усіма функціями редагування документів Collabora Online. Легко встановити, для особистого використання або для невеликих команд. Трохи повільніше, ніж окремий сервер, і без розширених функцій масштабування. Завантаження досить велике, тому під час використання веб-інтерфейсу може виникнути тайм-аут. Щоб установити вбудований сервер, можна скористатися інструментом командного рядка OCC: ``` sudo -u wwwrun php -d memory_limit=512M ./occ app:install richdocumentscode ``` Де `wwwrun` — це користувач вашого веб-сервера. Це ``www-data``` для Debian, Ubuntu і похідних, `wwwrun` для дистрибутивів на основі SUSE, `apache` на Red Hat/Fedora та `http` на Arch Linux і похідних. Оновлення можна виконати так: ``` sudo -u wwwrun php -d memory_limit=512M ./occ app:update --all ``` Звичайно, ви також можете збільшити використання пам’яті та тайм-аути PHP за замовчуванням, перегляньте [документацію Nextcloud.](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=php%20timeout). #налаштування-вашого-веб-сервера)",
    "Your system is ARM64, but you have installed the x86_64 version of the app. Please remove this and" : "Ваша система ARM64, але ви встановили версію програми x86_64. Будь ласка, видаліть це і",
    "install the correct version from the Nextcloud App Store." : "встановіть правильну версію з Nextcloud App Store.",
    "Your system is x86_64, but you have installed the ARM64 version of the app. Please remove this and" : "Ваша система x86_64, але ви встановили версію програми ARM64. Будь ласка, видаліть це і",
    "You have the Collabora Online app enabled. For further information and configuration, please check:" : "У вас увімкнено програму Collabora Online. Для отримання додаткової інформації та конфігурації, будь ласка, перевірте:",
    "Settings > Administration > Collabora Online" : "Налаштування > Адміністрування > Collabora Online",
    "Built-in CODE server is designed to work with the usual Collabora Online app." : "Вбудований сервер CODE призначений для роботи зі звичайним застосунком Collabora Online.",
    "Install it from the Nextcloud App Store." : "Установіть його з Nextcloud App Store.",
    "An error occurred while trying to check your Collabora Online app installation. You may report this error\n                with the tag: <em>richdocuments-EnabledCheckFailed</em>" : "Під час спроби перевірити встановлення програми Collabora Online сталася помилка. Ви можете повідомити про цю помилку за допомогою мітки: <em>richdocuments-EnabledCheckFailed</em>"
},
"nplurals=4; plural=(n % 1 == 0 && n % 10 == 1 && n % 100 != 11 ? 0 : n % 1 == 0 && n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 12 || n % 100 > 14) ? 1 : n % 1 == 0 && (n % 10 ==0 || (n % 10 >=5 && n % 10 <=9) || (n % 100 >=11 && n % 100 <=14 )) ? 2: 3);");
