OC.L10N.register(
    "richdocumentscode",
    {
    "Built-in CODE Server" : "內建的 CODE 伺服器",
    "Collabora Online - Built-in CODE Server" : "Collabora Online - 內建的 CODE 伺服器",
    "Built-in Collabora Online Development Edition (CODE) server for local testing and non-production use" : "供本機測試與非生產用途的內建 Collabora Online 開發版本（CODE）伺服器",
    "This app has to be installed and used together with the **[Collabora Online](https://apps.nextcloud.com/apps/richdocuments)** app.\n\nCollabora Online is a powerful LibreOffice-based online office suite with collaborative editing, which supports all major documents, spreadsheet and presentation file formats and works together with all modern browsers.\n\nThis app provides a built-in server with all of the document editing features of Collabora Online. Easy to install, for personal use or for small teams. A bit slower than a standalone server and without the advanced scalability features.\n\nThe download is rather big so it is possible you experience a time-out when using the web interface. You can use the OCC command line tool to install the built-in server:\n\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:install richdocumentscode\n```\nWhere `wwwrun` is the user of your web server. This is ```www-data``` on Debian, Ubuntu and derivatives, `wwwrun` on SUSE based distributions, `apache` on Red Hat/Fedora and `http` on Arch linux and derivatives.\n\nUpdates can be done like this:\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:update --all\n```\n\nOf course, alternatively you could increase memory usage and PHP time-outs by default, see the [Nextcloud documentation.](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=php%20timeout#configuring-your-web-server)" : "此應用程式必須與 **[Collabora Online]（https://apps.nextcloud.com/apps/richdocuments）** 應用程式一起安裝與使用。\n\nCollabora Online 是一套以 LibreOffice 為基礎的線上辦公室套裝軟體，可用來協作編輯，支援所有主要文件、試算表與簡報檔案格式，並可與所有現代的瀏覽器共同運作。\n\n此應用程式提供了包含所有 Collabora Online 文件編輯功能的內建伺服器。易於安裝，供個人或小型團隊使用。比獨立伺服器慢一點，且無進階的可延展功能。\n\n下載容量較大，因此若您使用網頁界面安裝，可能會遇到逾時的問題。您可以使用 OCC 指令列工具來安裝內建伺服器。\n\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:install richdocumentscode\n```\n`wwwrun` 是您的網路伺服器執行時的用戶身分。這在 Debian、Ubuntu 與其他衍生散佈版會是 ```www-data``` ，以 SUSE 為基礎的散佈版為 `wwwrun` ，Red Hat 與 Fedora 的衍生散佈版為 `apache` 以及 Arch Linux 與其衍生版本為 `http` 。\n\n更新可以像這樣完成：\n```\nsudo -u wwwrun php -d memory_limit=512M ./occ app:update --all\n```\n\n當然，您也可以增加 PHP 記憶體使用量與逾時的預設值，請看 [Nextcloud 文件]（https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=php%20timeout#configuring-your-web-server）。",
    "Your system is ARM64, but you have installed the x86_64 version of the app. Please remove this and" : "您的系統為 ARM64，但您安裝了 x86_64 版本的應用程式。請移除這個，然後",
    "install the correct version from the Nextcloud App Store." : "從 Nextcloud 的 App Store 安裝正確的版本。",
    "Your system is x86_64, but you have installed the ARM64 version of the app. Please remove this and" : "您的系統為 x86_64，但您安裝了 ARM64 版本的應用程式。請移除這個，然後",
    "You have the Collabora Online app enabled. For further information and configuration, please check:" : "您啟用了 Collabora Online 應用程式。要取得更多資訊與設定，請見：",
    "Settings > Administration > Collabora Online" : "設定 > 管理 > Collabora Online",
    "Built-in CODE server is designed to work with the usual Collabora Online app." : "內建的 CODE 伺服器旨在與一般的 Collabora Online 應用程式一起使用。",
    "Install it from the Nextcloud App Store." : "從Nextcloud 的 App Store安裝它。",
    "An error occurred while trying to check your Collabora Online app installation. You may report this error\n                with the tag: <em>richdocuments-EnabledCheckFailed</em>" : "嘗試檢查您的 Collabora Online 應用程式安裝時遇到錯誤。您可以使用此標籤\n                舉報此錯誤：<em>richdocuments-EnabledCheckFailed</em>"
},
"nplurals=1; plural=0;");
